In [5]:
#@save
import mxnet

print("done")

done


# 2. Preliminary  

In [2]:
from mxnet import np, npx

In [4]:
x = np.arange(12)
x

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [5]:
x.shape

(12,)

In [6]:
x.size

12

In [9]:
X = x.reshape(3, 4)
X

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [10]:
np.zeros((2, 3, 4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [11]:
np.ones((2, 3, 4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [12]:
np.random.normal(0, 1, size=(3, 4))

array([[ 1.1630785 ,  2.2122061 ,  0.4838046 ,  0.7740038 ],
       [ 0.29956347,  1.0434403 ,  0.15302546,  1.1839255 ],
       [-1.1688148 ,  1.8917114 ,  1.558071  , -1.2347414 ]])

In [13]:
np.array([
    [2, 1, 4, 3],
    [1, 2, 3, 4],
    [4, 3, 2, 1]
])

array([[2., 1., 4., 3.],
       [1., 2., 3., 4.],
       [4., 3., 2., 1.]])

## 2.2.1 Reading the Dataset

In [14]:
import os

In [ ]:
# !pip install pandas

In [22]:
import pandas as pd

In [30]:
dir_path = os.path.join('..', 'data')
os.makedirs(dir_path, exist_ok=True)

data_file = os.path.join(dir_path, 'house_tiny.csv')

with open(data_file, mode='w') as f:
    f.write('NumRooms, alley, Prices\n')
    f.write('NA,Pave,127500\n')
    f.write('2,NA,106000\n')
    f.write('4,NA,78100\n')
    f.write('NA,NA,140000\n')

In [31]:
data = pd.read_csv(data_file)
data

NumRooms  alley   Prices
0       NaN   Pave   127500
1       2.0    NaN   106000
2       4.0    NaN    78100
3       NaN    NaN   140000

## Missing Data

In [32]:
inputs = data.iloc[:, 0:2]
outputs = data.iloc[:, 2]

inputs = inputs.fillna(inputs.mean())  # Fill NA value to Missing data
inputs

NumRooms  alley
0       3.0   Pave
1       2.0    NaN
2       4.0    NaN
3       3.0    NaN

In [33]:
inputs = pd.get_dummies(inputs, dummy_na = True)
inputs

NumRooms   alley_Pave   alley_nan
0       3.0            1           0
1       2.0            0           1
2       4.0            0           1
3       3.0            0           1

In [34]:
X, y = np.array(inputs.values), np.array(outputs.values)
X, y

(array([[3., 1., 0.],
        [2., 0., 1.],
        [4., 0., 1.],
        [3., 0., 1.]], dtype=float64),
 array([127500, 106000,  78100, 140000], dtype=int64))